// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/load_balancing_policies/cluster_provided/v3/cluster_provided.proto

package cluster_providedv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ClusterProvided with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ClusterProvided) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClusterProvided with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClusterProvidedMultiError, or nil if none found.
func (m *ClusterProvided) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterProvided) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ClusterProvidedMultiError(errors)
	}

	return nil
}

// ClusterProvidedMultiError is an error wrapping multiple validation errors
// returned by ClusterProvided.ValidateAll() if the designated constraints
// aren't met.
type ClusterProvidedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterProvidedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterProvidedMultiError) AllErrors() []error { return m }

// ClusterProvidedValidationError is the validation error returned by
// ClusterProvided.Validate if the designated constraints aren't met.
type ClusterProvidedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterProvidedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterProvidedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterProvidedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterProvidedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterProvidedValidationError) ErrorName() string { return "ClusterProvidedValidationError" }

// Error satisfies the builtin error interface
func (e ClusterProvidedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterProvided.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterProvidedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterProvidedValidationError{}
